version: '3'
services:
  mysite:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile # Dockerfileのディレクトリを指定します
    volumes:
      - '../web:/game_review'
    ports:
      - "50030:8000" # 左側が外部からのアクセス時のポート番号:右側がdockerコンテナからアクセスする時のポート番号。ホストの8000番からコンテナの8000番へポートフォワードしています
    container_name: docker_game_review
    tty: true # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    working_dir: '/game_review'
    command: python3 ./game_review/manage.py runserver 0:8000
    links:
      - selenium
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: 'django.selenium'
    ports:
      - 4444:4444
      - 5900:5900


