version: '3'
services:
  mysite:
    build:
      context: ../
      dockerfile: ./docker/django/Dockerfile # Dockerfileのディレクトリを指定します
    volumes:
      - ../web:/game_review
    ports:
      - "50030:8000" # 左側が外部からのアクセス時のポート番号:右側がdockerコンテナからアクセスする時のポート番号。ホストの8000番からコンテナの8000番へポートフォワードしています
    command: sh -c "/game_review/game_review/entrypoint.sh"
    container_name: docker_game_review
    tty: true # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    working_dir: /game_review
    networks:
      - web
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: django.selenium
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - web
networks:
    web:
